/**
 * Workflow YAML Generator
 *
 * Converts type-safe WorkflowDefinition objects into GitHub Actions YAML.
 * This is the "compiler" from TypeScript types to executable CI/CD configuration.
 */

import * as yaml from 'yaml';
import { type WorkflowDefinition } from '../types/index.js';

/**
 * Serialize a workflow definition to GitHub Actions YAML.
 *
 * @param definition - Type-safe workflow definition
 * @returns Valid GitHub Actions YAML string
 */
export function toGitHubActionsYAML(definition: WorkflowDefinition): string {
  const doc = new yaml.Document(definition as unknown as yaml.Document);

  // Ensure proper quoting for expressions
  const yamlString = doc.toString({
    lineWidth: 120,
    indentSeq: true,
  });

  // Add header comment
  const header = `# =============================================================================
# Auto-generated by Golden Path Framework
# DO NOT EDIT MANUALLY — Modify the TypeScript source and run:
#   pnpm generate-workflows
# =============================================================================
# Generated at: ${new Date().toISOString()}
# Framework version: 0.1.0
# =============================================================================\n\n`;

  return header + yamlString;
}

/**
 * Write workflow definition to a file.
 */
import * as fs from 'fs';

export function writeWorkflow(definition: WorkflowDefinition, filePath: string): void {
  const yamlContent = toGitHubActionsYAML(definition);
  fs.writeFileSync(filePath, yamlContent, 'utf-8');
}

/**
 * Validate that a workflow definition has required fields.
 */
export function validateWorkflow(definition: WorkflowDefinition): string[] {
  const errors: string[] = [];

  if (!definition.name) {
    errors.push('Workflow must have a name');
  }

  if (!definition.on || Object.keys(definition.on).length === 0) {
    errors.push('Workflow must define triggers (on:)');
  }

  if (!definition.jobs || Object.keys(definition.jobs).length === 0) {
    errors.push('Workflow must have at least one job');
  }

  for (const [jobId, job] of Object.entries(definition.jobs)) {
    if (!job['runs-on']) {
      errors.push(`Job '${jobId}' must specify 'runs-on'`);
    }
    if (!job.steps || job.steps.length === 0) {
      errors.push(`Job '${jobId}' must have at least one step`);
    }
    for (const [i, step] of job.steps.entries()) {
      if (!step.name) {
        errors.push(`Job '${jobId}', step ${i} must have a name`);
      }
      if (!step.uses && !step.run) {
        errors.push(`Job '${jobId}', step '${step.name}' must have 'uses' or 'run'`);
      }
    }
  }

  return errors;
}
