"""Git hooks management for pre-push validation.

Installs and manages git hooks that enforce:
- Work ID validation
- Standards checks
- Unit test execution
- Linting
"""

from __future__ import annotations

import stat
from pathlib import Path

from rich.console import Console

console = Console()

PRE_PUSH_HOOK = """#!/bin/bash
# ============================================================
# Golden Path Pre-Push Hook
# Auto-generated by goldenpath-cli
# DO NOT EDIT MANUALLY — Run `goldenpath hooks install` to update
# ============================================================

set -euo pipefail

echo "🔒 Golden Path Pre-Push Validation Starting..."

# Run standards check
echo "📋 Running standards check..."
goldenpath standards --strict

# Validate Work ID in commits
echo "🆔 Validating Work ID compliance..."
goldenpath validate work-id

# Run project-specific tests (detected by language)
echo "🧪 Running pre-push tests..."
if [ -f "pytest.ini" ] || [ -f "pyproject.toml" ]; then
    echo "   Detected Python project — running pytest..."
    uv run pytest tests/ -q --tb=short || python -m pytest tests/ -q --tb=short
elif [ -f "package.json" ]; then
    echo "   Detected Node.js project — running pnpm test..."
    pnpm test -- --run || npm test -- --run
elif [ -f "go.mod" ]; then
    echo "   Detected Go project — running go test..."
    go test ./... -short
else
    echo "   ⚠️  No recognized test framework found. Skipping tests."
fi

echo "✅ Golden Path Pre-Push Validation Complete"
"""

COMMIT_MSG_HOOK = """#!/bin/bash
# ============================================================
# Golden Path Commit Message Hook
# Ensures Work ID is present in commit messages
# ============================================================

COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(head -n1 "$COMMIT_MSG_FILE")

# Allow merge commits
if echo "$COMMIT_MSG" | grep -qE "^Merge"; then
    exit 0
fi

# Check for Work ID pattern (e.g., FIN-123)
if ! echo "$COMMIT_MSG" | grep -qE '[A-Z]+-[0-9]+'; then
    echo "❌ Commit message must include a Work ID (e.g., FIN-123)"
    echo "   Example: [FIN-123] feat: add payment validation"
    exit 1
fi

exit 0
"""


class HookManager:
    """Manages Git hooks installation and lifecycle."""

    def __init__(self, repo_path: Path | None = None) -> None:
        self.repo_path = repo_path or Path.cwd()
        self.hooks_dir = self.repo_path / ".git" / "hooks"

    def install_pre_push(self) -> None:
        """Install pre-push hook."""
        hook_path = self.hooks_dir / "pre-push"
        hook_path.write_text(PRE_PUSH_HOOK, encoding="utf-8")
        hook_path.chmod(hook_path.stat().st_mode | stat.S_IEXEC)
        console.print(f"[green]✓[/green] Installed pre-push hook at {hook_path}")

    def install_commit_msg(self) -> None:
        """Install commit-msg hook."""
        hook_path = self.hooks_dir / "commit-msg"
        hook_path.write_text(COMMIT_MSG_HOOK, encoding="utf-8")
        hook_path.chmod(hook_path.stat().st_mode | stat.S_IEXEC)
        console.print(f"[green]✓[/green] Installed commit-msg hook at {hook_path}")

    def install_all(self) -> None:
        """Install all Golden Path hooks."""
        if not self.hooks_dir.exists():
            console.print("[red]✗[/red] No .git/hooks directory found. Are you in a Git repository?")
            return
        self.install_pre_push()
        self.install_commit_msg()
        console.print("[bold green]All hooks installed successfully![/bold green]")

    def uninstall_all(self) -> None:
        """Remove Golden Path managed hooks."""
        for hook_name in ("pre-push", "commit-msg"):
            hook_path = self.hooks_dir / hook_name
            if hook_path.exists() and "Golden Path" in hook_path.read_text(encoding="utf-8"):
                hook_path.unlink()
                console.print(f"[yellow]−[/yellow] Removed {hook_name} hook")
        console.print("[bold yellow]Golden Path hooks removed.[/bold yellow]")
