"""Local environment bootstrap for cloud-free development.

Generates docker-compose.local.yml with LocalStack and any service-specific
dependencies so teams can run tests without AWS latency.
"""

from __future__ import annotations

from pathlib import Path

from rich.console import Console

from goldenpath_cli.config import ProjectConfig

console = Console()

# fmt: off
DOCKER_COMPOSE_TEMPLATE = """# =============================================================================
# Golden Path — Local Development Environment
# Auto-generated by goldenpath-cli
# =============================================================================
version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES={services}
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LS_LOG=warn
    volumes:
      - "${{LOCALSTACK_VOLUME_DIR:-./.localstack}}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # DynamoDB Admin UI (optional)
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
    profiles:
      - tools

networks:
  default:
    name: goldenpath-local
"""
# fmt: on

LOCALSTACK_INIT_SCRIPT = """#!/bin/bash
# =============================================================================
# LocalStack Initialization Script
# Run after `docker compose up` to seed initial resources
# =============================================================================

set -e

ENDPOINT_URL="http://localhost:4566"
echo "Initializing LocalStack resources..."

# DynamoDB Table
echo "Creating DynamoDB table: Transactions..."
aws dynamodb create-table \\
    --endpoint-url $ENDPOINT_URL \\
    --table-name Transactions \\
    --attribute-definitions AttributeName=transactionId,AttributeType=S \\
    --key-schema AttributeName=transactionId,KeyType=HASH \\
    --billing-mode PAY_PER_REQUEST \\
    --region us-east-1 || true

echo "LocalStack initialization complete!"
"""

PYTHON_TEST_CONFIG = """# pytest.ini — Local Test Configuration
[pytest]
testpaths = tests
pythonpath = src
addopts = -v --tb=short
env =
    AWS_ACCESS_KEY_ID=testing
    AWS_SECRET_ACCESS_KEY=testing
    AWS_DEFAULT_REGION=us-east-1
    AWS_ENDPOINT_URL=http://localhost:4566
    STAGE=local
"""


class LocalEnvBootstrap:
    """Bootstraps local development environment."""

    def __init__(self, config: ProjectConfig) -> None:
        self.config = config
        self.local_config = config.local_env

    def generate_docker_compose(self, output_path: Path | None = None) -> Path:
        """Generate docker-compose.local.yml (uses modern `docker compose` plugin)."""
        path = output_path or Path(self.local_config.docker_compose_path)
        services = ",".join(self.local_config.localstack_services)
        content = DOCKER_COMPOSE_TEMPLATE.format(services=services)
        path.write_text(content, encoding="utf-8")
        console.print(f"[green]✓[/green] Generated {path}")
        return path

    def generate_init_script(self, output_path: Path | None = None) -> Path:
        """Generate LocalStack init script."""
        path = output_path or Path("scripts/init-localstack.sh")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(LOCALSTACK_INIT_SCRIPT, encoding="utf-8")
        path.chmod(0o755)
        console.print(f"[green]✓[/green] Generated {path}")
        return path

    def generate_test_config(self) -> None:
        """Generate language-specific test configuration."""
        if self.config.language == "python":
            path = Path("pytest.ini")
            if not path.exists():
                path.write_text(PYTHON_TEST_CONFIG, encoding="utf-8")
                console.print(f"[green]✓[/green] Generated {path}")

    def bootstrap(self) -> None:
        """Run full local environment bootstrap."""
        console.print("[bold blue]🚀 Bootstrapping Local Development Environment...[/bold blue]")
        self.generate_docker_compose()
        self.generate_init_script()
        self.generate_test_config()
        console.print("[bold green]✅ Local environment ready![/bold green]")
        console.print("\nNext steps:")
        console.print("  1. docker compose -f docker-compose.local.yml up -d")
        console.print("  2. ./scripts/init-localstack.sh")
        console.print("  3. Run tests locally with no cloud latency")
