/**
 * Framework Unit Tests
 *
 * Evidence of test suite setup and testing criteria.
 */

import { describe, it, expect } from 'vitest';
import { ServiceStack } from '../src/constructs/service-stack.js';
import { generatePRPipeline } from '../src/workflows/pr-pipeline.js';
import { generateIntegrationPipeline } from '../src/workflows/integration-pipeline.js';
import { toGitHubActionsYAML, validateWorkflow } from '../src/pipelines/generator.js';
import { DoraTelemetry } from '../src/dora/telemetry.js';
import { App } from 'aws-cdk-lib';
import { Template } from 'aws-cdk-lib/assertions';

// ── Workflow Tests ───────────────────────────────────────────────────────────

describe('PR Pipeline Generator', () => {
  it('should generate a workflow with required jobs', () => {
    const workflow = generatePRPipeline({
      serviceName: 'transactionify',
      language: 'python',
      cdkStack: 'TransactionifyStack',
    });

    expect(workflow.name).toContain('transactionify');
    expect(workflow.jobs).toHaveProperty('detect-work-id');
    expect(workflow.jobs).toHaveProperty('small-tests');
    expect(workflow.jobs).toHaveProperty('security-scan');
    expect(workflow.jobs).toHaveProperty('standards-check');
  });

  it('should include sandbox deployment when enabled', () => {
    const workflow = generatePRPipeline({
      serviceName: 'transactionify',
      language: 'python',
      cdkStack: 'TransactionifyStack',
      enableSandboxDeploy: true,
    });

    expect(workflow.jobs).toHaveProperty('deploy-sandbox');
    const deployJob = workflow.jobs['deploy-sandbox'];
    expect(deployJob?.if).toContain('deploy:sandbox');
  });

  it('should validate as a correct workflow', () => {
    const workflow = generatePRPipeline({
      serviceName: 'transactionify',
      language: 'python',
    });

    const errors = validateWorkflow(workflow);
    expect(errors).toHaveLength(0);
  });
});

describe('Integration Pipeline Generator', () => {
  it('should generate staging and production jobs', () => {
    const workflow = generateIntegrationPipeline({
      serviceName: 'transactionify',
      language: 'python',
      cdkStack: 'TransactionifyStack',
      stagingRoleArn: 'arn:aws:iam::123:role/staging',
      productionRoleArn: 'arn:aws:iam::123:role/production',
    });

    expect(workflow.jobs).toHaveProperty('deploy-staging');
    expect(workflow.jobs).toHaveProperty('deploy-production');
    expect(workflow.jobs).toHaveProperty('smoke-tests');
  });

  it('should trigger on main branch pushes', () => {
    const workflow = generateIntegrationPipeline({
      serviceName: 'transactionify',
      language: 'python',
      cdkStack: 'TransactionifyStack',
      stagingRoleArn: 'arn:aws:iam::123:role/staging',
      productionRoleArn: 'arn:aws:iam::123:role/production',
    });

    expect(workflow.on).toHaveProperty('push');
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    expect((workflow.on as Record<string, unknown>).push).toEqual(
      expect.objectContaining({ branches: ['main'] })
    );
  });
});

describe('YAML Generator', () => {
  it('should produce valid YAML with header comment', () => {
    const workflow = generatePRPipeline({
      serviceName: 'tx',
      language: 'python',
    });

    const yaml = toGitHubActionsYAML(workflow);
    expect(yaml).toContain('Auto-generated by Golden Path Framework');
    expect(yaml).toContain('name:');
    expect(yaml).toContain('jobs:');
  });
});

// ── CDK Construct Tests ──────────────────────────────────────────────────────

describe('ServiceStack', () => {
  it('should synthesize without errors', () => {
    const app = new App();

    const stack = new ServiceStack(app, 'TestStack', {
      serviceName: 'test-service',
      team: 'platform',
      environment: 'sandbox',
      runtime: 'python3.12',
      language: 'python',
      handlers: [
        { name: 'Process', path: 'src/process.py' },
      ],
      apiRoutes: [
        { path: '/process', method: 'POST', handler: 'Process' },
      ],
      enableDynamoDB: true,
    });

    expect(stack.api).toBeDefined();
    expect(stack.functions.has('Process')).toBe(true);
    expect(stack.table).toBeDefined();
    expect(stack.topic).toBeDefined();
  });

  it('should tag resources correctly', () => {
    const app = new App();
    const stack = new ServiceStack(app, 'TestStack2', {
      serviceName: 'test-service',
      team: 'platform',
      environment: 'staging',
      runtime: 'nodejs20.x',
      language: 'typescript',
      handlers: [{ name: 'Handler', path: 'src/index.ts' }],
      apiRoutes: [{ path: '/', method: 'GET', handler: 'Handler' }],
    });

    const template = Template.fromStack(stack);
    const lambda = template.findResources('AWS::Lambda::Function');
    const handlerKey = Object.keys(lambda).find((k) => k.startsWith('Handler'));
    expect(handlerKey).toBeDefined();
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
    const tags = lambda[handlerKey!].Properties.Tags as Array<{ Key: string; Value: string }>;
    const tagMap = Object.fromEntries(tags.map((t) => [t.Key, t.Value]));
    expect(tagMap['service']).toBe('test-service');
    expect(tagMap['team']).toBe('platform');
    expect(tagMap['managed-by']).toBe('goldenpath-framework');
  });
});

// ── DORA Telemetry Tests ─────────────────────────────────────────────────────

describe('DoraTelemetry', () => {
  it('should record deployment events', () => {
    const telemetry = new DoraTelemetry({ project: 'tx' });
    const event = telemetry.recordDeployment({
      workId: 'FIN-123',
      commitSha: 'abc123',
      environment: 'staging',
      success: true,
    });

    expect(event.eventType).toBe('deployment');
    expect(event.workId).toBe('FIN-123');
    expect(event.success).toBe(true);
    expect(event.environment).toBe('staging');
    expect(event.timestamp).toBeDefined();
  });

  it('should record failure events', () => {
    const telemetry = new DoraTelemetry({ project: 'tx' });
    const event = telemetry.recordFailure({
      workId: 'FIN-456',
      commitSha: 'def789',
      errorMessage: 'Deployment timeout',
    });

    expect(event.eventType).toBe('failure');
    expect(event.success).toBe(false);
    expect(event.metadata).toHaveProperty('error', 'Deployment timeout');
  });

  it('should create audit context', () => {
    const audit = DoraTelemetry.createAuditContext({
      actor: 'dev@example.com',
      action: 'deploy',
      reason: 'release',
    });

    expect(audit.actor).toBe('dev@example.com');
    expect(audit.action).toBe('deploy');
    expect(audit.complianceFramework).toBe('soc2');
  });
});
